name: Build-and-Publish-Back

on:
  push:
    branches: [master]
    paths:
      - server/**
  pull_request:
    branches: [master]
    paths:
      - server/**
  workflow_dispatch:

jobs:
  build-and-push-docker-image:
    name: Build cryptography-web-back and push to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: v3
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build image and push to Docker Hub
        uses: docker/build-push-action@v3
        with:
          context: ./server
          tags: ${{ secrets.DOCKERHUB_USER }}/cryptography-web-back:latest
          push: true
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }} >> $GITHUB_OUTPUT