name: Build-and-Publish-Back

on:
  push:
    branches: [master]
    paths:
      - server/**
  pull_request:
    branches: [master]
    paths:
      - server/**
  workflow_dispatch:

jobs:
  build-and-push-docker-image:
    name: Build cryptography-web-back and push to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: master
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build image and push to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: ./server
          tags: ${{ secrets.DOCKERHUB_USER }}/cryptography-web-back:latest
          push: true
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }} >> $GITHUB_OUTPUT
      - name: Check status of cryptography-web
        continue-on-error: true
        id: check-cryptography-web
        uses: jtalk/url-health-check-action@v4
        with:
          url: ${{ vars.WEBSITE_ADDRESS }}
          max-attempts: 3
          retry-delay: 5s
      - name: Trigger cryptography-web deployment
        if: ${{ steps.check-cryptography-web.outcome == 'success' }}
        uses: peter-evans/repository-dispatch@v3
        with:
          repository: ${{ secrets.CRYPTOGRAPHY_WEB_DEPLOYMENT_REPO }}
          token: ${{ secrets.REMOTE_REPO_PAT }}
          event-type: deploy-cryptography-web